### ISSUE TITLE
Bug Report: Database issue prevents generation of analyzed.root file

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/gem-light-dqm#25]
## Brief summary of issue

Cannot produce `analyzed.root` file.  Some database issue generates a seg fault and crashes program.

### Types of issue

- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Should be able to produce the `analyzed.root` file.

## Current Behavior

```
[gemuser@gem904qc8daq dic]$ dqm /data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000061_LatencyScan_CERNQC8_2018-07-19_chunk_0.raw.root 
--==DQM Main==--
Error connecting to database '' : Can't connect to MySQL server on 'gem904daq01.cern.ch' (111)

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f3601f181c9 in waitpid () from /lib64/libc.so.6
#1  0x00007f3601e95e52 in do_system () from /lib64/libc.so.6
#2  0x00007f3601e96201 in system () from /lib64/libc.so.6
#3  0x00007f36080f24b2 in TUnixSystem::StackTrace() () from /usr/lib64/root/libCore.so.6.12
#4  0x00007f36080f4e2c in TUnixSystem::DispatchSignals(ESignals) () from /usr/lib64/root/libCore.so.6.12
#5  <signal handler called>
#6  0x00007f3603674e07 in mysql_send_query () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f3603674e41 in mysql_real_query () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x0000000000406786 in simpleDBQuery(st_mysql*, std::string) ()
#9  0x00000000004073e8 in getConfig(std::string) ()
#10 0x000000000040879d in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum.
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f3603674e07 in mysql_send_query () from /usr/lib64/mysql/libmysqlclient.so.18
#7  0x00007f3603674e41 in mysql_real_query () from /usr/lib64/mysql/libmysqlclient.so.18
#8  0x0000000000406786 in simpleDBQuery(st_mysql*, std::string) ()
#9  0x00000000004073e8 in getConfig(std::string) ()
#10 0x000000000040879d in main ()
===========================================================
```

### Steps to Reproduce (for bugs)

1. `cd $BUILD_HOME/gem-light-dqm/gemtreewriter/src/dic/`
2. `dqm $DATA_PATH/Cosmics/run000061_LatencyScan_CERNQC8_2018-07-19_chunk_0.raw.root`

## Context (for feature requests)

Cannot analyze data taken.

## Your Environment

* Version used:
* Shell used:

**Comment by mexanick** [comment]
please provide version of code you used

**Comment by mexanick** [comment]
@bdorney is this issue still valid? Does it refer to V2 or V3 electronics?

**Comment by bdorney** [comment]
Honestly I have no idea.  I didn't provide enough debugging info here (my bad) and I wasn't able to repeat the issue the other day.  I think we can close this for now and if I run into it again I will reopen and provide better info.
