### ISSUE TITLE
Histogram not filled for latency scan(m_RunType = 2)

### ISSUE THREAD

**Issue by JohnyJaramillo** [cms-gem-daq-project/gem-light-dqm#44]
## Brief summary of issue
Latency scans shows values in cero for all the OH in the cosmic stand.

### Types of issue

- [X] Bug report (report an issue with the code)
- [  ] Feature request (request for change which adds functionality)

## Current Behavior
```bash
*.raw files copied to NAS and located in:
/data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/

unpacker (ferol) and LightDQM executed using runLDQM.sh script:
runLDQM.sh -i 1 -r 456

Normal termination, output file:
/data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/run000456_allLumi_index000000.analyzed.root

Analysis script shows a bug:
[gemuser@gem904qc8daq ~]$ anaXDAQLatency.py -s 6 --scanmin 50 --scanmax 75 /data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/run000456_allLumi_index000000.analyzed.root
Traceback (most recent call last):
  File "/opt/cmsgemos/bin/anaXDAQLatency.py", line 50, in 
    if 'gemType' not in inFile.latTree.GetListOfBranches():
NameError: name 'inFile' is not defined
[gemuser@gem904qc8daq ~]$ 

Fix hardcoded in local copy:
cd /home/gemuser/fsimone
python anaXDAQLatency.py -s 6 --scanmin 50 --scanmax 75 /data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/run000456_allLumi_index000000.analyzed.root -r 456
```
Output plots are empty

### Steps to Reproduce (for bugs)

1. run in QC8 machine: 
```bash
[gemuser@gem904qc8daq ~]$ anaXDAQLatency.py -s 6 --scanmin 50 --scanmax 75 /data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/run000456_allLumi_index000000.analyzed.root
```

## Your Environment

* Version used:
* Shell used:

**Comment by cgalloni** [comment]
> ```shell
> Analysis script shows a bug:
> [gemuser@gem904qc8daq ~]$ anaXDAQLatency.py -s 6 --scanmin 50 --scanmax 75 /data/bigdisk/GEM-Data-Taking/GE11_QC8/Cosmics/run000456/run000456_allLumi_index000000.analyzed.root
> Traceback (most recent call last):
>   File "/opt/cmsgemos/bin/anaXDAQLatency.py", line 50, in 
>   
> ```

this will be fixed in  [PR#291 ](https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/291#pullrequestreview-372196471)

The problem is in the unpacker version installed on `gem904qc8daq`  which doesn't fll the relevant histograms for a latency scan (m_RunType = 2)

https://github.com/cms-gem-daq-project/gem-light-dqm/blob/develop/dqm-root/src/common/gemTreeReader.cxx#L221

**Comment by lpetre-ulb** [comment]
Since the main issue looks like a lack of update due to a lack of releasing (because of the workaround used to reduced memory consumption), shouldn't something be done for the legacy release? I also see many branches, some of them having already been merged.

Wouldn't it be good to create one `release/legacy` branch like in the other repositories as well as one branch per setup at CERN, based on that branch? @mexanick?

**Comment by mexanick** [comment]
Yes, this makes sense. I have to think a bit on how to do that more accurately, eventually avoiding the extra branches. I will expand at tomorrow's dev meeting on this.
